services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    # ports:
    #   - "8001:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/users`) || PathPrefix(`/docs`) || PathPrefix(`/openapi.json`)"
      - "traefik.http.services.user-service.loadbalancer.server.port=8000"
    
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - product-service
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile


volumes:
  postgres_data: