apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://admin:admin%40123@postgres:5432/appdb"
  SECRET_KEY: "my_super_secret_jwt_key_for_microservices"