apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PRODUCT_SERVICE_HOST: "product-service"
  PRODUCT_SERVICE_PORT: "50051"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  CORS_ORIGINS: "*"
  ALGORITHM: "HS256"